encoding: utf-8
exclude:
  - LICENSE
  - README.md
  - res
url: https://fontefideliti.ru
destination: public

collections:
  shows:
    permalink: /shows/:name.htm
    output: true

defaults:
  - scope:
      type: shows
    values:
      layout: global_shows

compress_html:
  clippings: all

plugins:
  - jekyll-redirect-from
