name: Build and Deploy

on:
  push:
    branches:
    - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Set up Repo Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Create a Build Directory
        run: mkdir public
      - name: Build Site Content
        run: python ../src/build_site.py ../res
        working-directory: ./public
      - name: Cache Build Artifacts
        uses: actions/cache@v2
        with:
          path: |
            public
            firebase.json
          key: build-${{ github.sha }}

  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifact Cache
        uses: actions/cache@v2
        with:
          path: |
            public
            firebase.json
          key: build-${{ github.sha }}
      - name: Validate Hyperlink and Image Targets
        uses: chabad360/htmlproofer@master
        with:
          directory: "./public"
      - name: Validate HTML and CSS Conformance
        uses: Cyb3r-Jak3/html5validator-action@master
        with:
          css: true
          root: public/

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifact Cache
        uses: actions/cache@v2
        with:
          path: |
            public
            firebase.json
          key: build-${{ github.sha }}
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: fontefideliti
