name: Build and Deploy

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-python@v2
        with:
          python-version: 'pypy3'
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: mkdir public && cp -r ./{males,females,dogs.htm,style.css} ./public
      - run: python photo_generation.py public
      - run: python ../src/build_site.py ../res
        working-directory: ./public
      - uses: gha-utilities/sass-build@v0.3.7
        with:
          source: res/common.scss
          destination: public/common.css
      - uses: chabad360/htmlproofer@master
        with:
          directory: "./public"
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: fontefideliti
